name: Composer Update (PHP 7.4)

on:
  workflow_dispatch: {}

jobs:
  composer-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
      - name: Install system packages
        run: sudo apt-get update && sudo apt-get install -y unzip git
      - name: Setup composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
      - name: Composer update (selected safe packages)
        run: |
          composer config platform.php 7.4
          # Update only low-risk, semver-safe packages to avoid major-version blockers
          composer update barryvdh/laravel-debugbar filp/whoops laravel/tinker fzaninotto/faker --with-dependencies --no-interaction || true
      - name: Upload composer.lock
        uses: actions/upload-artifact@v4
        with:
          name: composer-lock
          path: composer.lock
